[project]
name = "Caffeine"
description = "Utilities for the Starbucks minecraft server."
version = "0.1.0"
natures = [ "eclipse", "maven" ]

[dependencies]
spigot-api-shaded = { type = "fetchFromMaven", url = "https://hub.spigotmc.org/nexus/repository/snapshots/", group_id = "org.spigotmc", artifact_id = "spigot-api", classifier = "shaded", javadoc = "https://hub.spigotmc.org/javadocs/spigot/" }
anenome = { type = "fetchFromGithub", username = "Khyonie", repository = "Anenome", tag = "v0.4.1" }
lilac = { type = "fetchFromGithub", username = "Khyonie", repository = "Lilac", tag = "v2.1.0-beta.1" }
tidal = { type = "fetchFromGithub", username = "Khyonie", repository = "Tidal", tag = "v2.1.0", asset = "Tidal-main-2.1.0" }

[configuration.main]
sources = [ "src/api/", "src/plugin/" ]
dependencies = [ "spigot-api-shaded", "anenome", "lilac", "tidal" ]
shaded = [ "anenome", "lilac" ]
targets = [ "targets/{configuration}/{project_name}-{configuration}-{version}.jar" ]
